name: deep-learning
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - absl-py=0.10.0=py37_0
  - argon2-cffi=20.1.0=py37h7b6447c_1
  - astor=0.8.1=py37_0
  - async_generator=1.10=py37h28b3542_0
  - attrs=20.2.0=py_0
  - backcall=0.2.0=py_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - binutils_impl_linux-64=2.31.1=h6176602_1
  - binutils_linux-64=2.31.1=h6176602_9
  - blas=1.0=openblas
  - bleach=3.2.1=py_0
  - brotlipy=0.7.0=py37h7b6447c_1000
  - c-ares=1.16.1=h7b6447c_0
  - ca-certificates=2020.6.20=hecda079_0
  - cairo=1.16.0=h18b612c_1001
  - certifi=2020.6.20=py37he5f6b98_2
  - cffi=1.14.3=py37he30daa8_0
  - chardet=3.0.4=py37_1003
  - cryptography=3.1.1=py37h1ba5d50_0
  - cycler=0.10.0=py37_0
  - dbus=1.13.18=hb2f20db_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - expat=2.2.10=he6710b0_2
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.4=h5ab3b9f_0
  - fribidi=1.0.10=h516909a_0
  - gast=0.4.0=py_0
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_9
  - gettext=0.19.8.1=h5e8e0c9_1
  - glib=2.66.1=h92f7085_0
  - google-pasta=0.2.0=py_0
  - graphite2=1.3.13=he1b5a44_1001
  - graphviz=2.42.3=h0511662_0
  - grpcio=1.31.0=py37hf8bcb03_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_9
  - h5py=2.10.0=nompi_py37hf7afa78_105
  - harfbuzz=2.4.0=hca77d97_0
  - hdf5=1.10.6=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - idna=2.10=py_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - ipykernel=5.3.4=py37h5ca1d4c_0
  - ipython=7.18.1=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - jedi=0.15.2=py37_0
  - jinja2=2.11.2=py_0
  - joblib=0.17.0=py_0
  - jpeg=9d=h516909a_0
  - json5=0.9.5=py_0
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.6.3=py37_0
  - jupyterlab=2.2.6=py_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=1.2.0=py_0
  - keras=2.3.1=0
  - keras-applications=1.0.8=py_1
  - keras-base=2.3.1=py37_0
  - keras-preprocessing=1.1.0=py_1
  - kernel-headers_linux-64=2.6.32=h77966d4_13
  - kiwisolver=1.2.0=py37hfd86e86_0
  - krb5=1.18.2=h173b8e3_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libcurl=7.71.1=h20c2e04_1
  - libedit=3.1.20191231=h14c3975_1
  - libev=4.33=h7b6447c_0
  - libffi=3.3=he6710b0_2
  - libgcc-devel_linux-64=7.5.0=h42c25f5_16
  - libgcc-ng=9.3.0=h24d8f2e_16
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libgomp=9.3.0=h24d8f2e_16
  - libgpuarray=0.7.6=h14c3975_0
  - liblapack=3.8.0=17_openblas
  - libnghttp2=1.41.0=hf8bcb03_2
  - libopenblas=0.3.10=h5a2b251_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.13.0.1=hd408876_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-devel_linux-64=7.5.0=h4084dd6_16
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libtool=2.4.6=hebb1f50_1006
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h7b6447c_3
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.2=heb0550a_3
  - mako=1.1.3=py_0
  - markdown=3.3.2=py37_0
  - markupsafe=1.1.1=py37h14c3975_1
  - matplotlib=3.3.1=0
  - matplotlib-base=3.3.1=py37h817c723_0
  - mistune=0.8.4=py37h14c3975_1001
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py37_0
  - nbformat=5.0.8=py_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.4.1=py_0
  - notebook=6.1.4=py37_0
  - numpy=1.19.1=py37h30dfecb_0
  - numpy-base=1.19.1=py37h75fe3a5_0
  - olefile=0.46=py37_0
  - openblas=0.3.4=h9ac9557_1000
  - openssl=1.1.1h=h516909a_0
  - packaging=20.4=py_0
  - pandas=1.1.3=py37he6710b0_0
  - pandoc=2.11=hb0f4dca_0
  - pandocfilters=1.4.2=py37_1
  - pango=1.42.4=h7062337_4
  - parso=0.5.2=py_0
  - patsy=0.5.1=py37_0
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=py37_1
  - pickleshare=0.7.5=py37_1001
  - pillow=8.0.0=py37h9a89aac_0
  - pip=20.2.4=py37_0
  - pixman=0.38.0=h516909a_1003
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.8=py_0
  - protobuf=3.13.0.1=py37he6710b0_1
  - ptyprocess=0.6.0=py37_0
  - pycparser=2.20=py_2
  - pydot=1.2.4=py_0
  - pygments=2.7.1=py_0
  - pygpu=0.7.6=py37heb32a55_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.17.3=py37h7b6447c_0
  - pysocks=1.7.1=py37_1
  - python=3.7.9=h7579374_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.1=py_0
  - pyyaml=5.3.1=py37h7b6447c_1
  - pyzmq=19.0.2=py37he6710b0_1
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=py_0
  - scikit-learn=0.23.2=py37h0573a6f_0
  - scipy=1.5.2=py37habc2bb6_0
  - seaborn=0.11.0=py_0
  - seaborn-base=0.11.0=py_0
  - send2trash=1.5.0=py37_0
  - setuptools=50.3.0=py37hb0f4dca_1
  - sip=4.19.8=py37hf484d3e_0
  - six=1.15.0=py_0
  - sqlite=3.33.0=h62c20be_0
  - statsmodels=0.12.0=py37h7b6447c_0
  - sysroot_linux-64=2.12=h77966d4_13
  - tensorboard=1.14.0=py37_0
  - tensorflow=1.14.0=h4531e10_0
  - tensorflow-base=1.14.0=py37h4531e10_0
  - tensorflow-estimator=1.14.0=py37h5ca1d4c_0
  - termcolor=1.1.0=py37_1
  - terminado=0.9.1=py37_0
  - testpath=0.4.4=py_0
  - theano=1.0.4=py37hfd86e86_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - tornado=6.0.4=py37h7b6447c_1
  - traitlets=5.0.5=py_0
  - urllib3=1.25.10=py_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py37_1
  - werkzeug=1.0.1=py_0
  - wheel=0.35.1=py_0
  - wrapt=1.12.1=py37h7b6447c_1
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxpm=3.5.13=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.3=he6710b0_3
  - zipp=3.3.1=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
prefix: /home/damase/miniconda3/envs/deep-learning
